const sampleListing = [
  {
    image: [
      "https://collegekeeda.com/wp-content/uploads/2023/12/COEP-Pune-1.webp",
    ],
    code: 101234,
    exam: "JEE, MHT-CET",
    name: "College of Engineering, Pune",
    location: "Pune, Maharashtra",
    type: "Autonomous",
    cutoff: 98,
    accreditation: "NAAC A++",
    fees: 125000,
    description:
      "Established in 1854, COEP is one of the oldest engineering colleges in Asia. It offers excellent infrastructure, experienced faculty, and strong industry connections with 90% placement rate. Hostel facilities available for both boys and girls.",
    rating: 4.8,
    establishedYear: 1854,
    affiliation: "Savitribai Phule Pune University",
    placementRate: 90,
    phoneNumber: 912025507000,
    email: "info@coep.ac.in",
    website: "https://www.coep.org.in",
  },
  {
    image: [
      "https://upload.wikimedia.org/wikipedia/commons/b/b4/VJTI_Quadrangle.jpg",
    ],
    code: 102345,
    exam: "MHT-CET, NEET",
    name: "Veermata Jijabai Technological Institute",
    location: "Mumbai, Maharashtra",
    type: "Autonomous",
    cutoff: 97,
    accreditation: "NAAC A+",
    fees: 85000,
    description:
      "VJTI is a premier technical institute in Mumbai with excellent placement records. Known for its mechanical and electrical engineering programs. The campus has modern labs, library, and sports facilities.",
    rating: 4.6,
    establishedYear: 1887,
    affiliation: "University of Mumbai",
    placementRate: 88,
    phoneNumber: 912224161111,
    email: "director@vjti.ac.in",
    website: "https://vjti.ac.in",
  },
  {
    image: [
      "https://images.careerindia.com/college-photos/8381/vnit-campus-1_1462173673.jpg",
    ],
    code: 103456,
    exam: "JEE, MHT-CET",
    name: "Visvesvaraya National Institute of Technology",
    location: "Nagpur, Maharashtra",
    type: "Autonomous",
    cutoff: 95,
    accreditation: "NAAC A",
    fees: 65000,
    description:
      "VNIT is an institute of national importance with excellent research facilities. Offers various undergraduate and postgraduate programs in engineering. Strong alumni network and industry collaborations.",
    rating: 4.5,
    establishedYear: 1960,
    affiliation: "NIT",
    placementRate: 85,
    phoneNumber: 917122222518,
    email: "director@vnit.ac.in",
    website: "https://vnit.ac.in",
  },
  {
    image: [
      "https://medicinecolleges.in/assets/colleges/1547/bannerimage1.jpg",
    ],
    code: 104567,
    exam: "NEET, AIIMS",
    name: "Grant Medical College",
    location: "Mumbai, Maharashtra",
    type: "Government",
    cutoff: 99,
    accreditation: "NAAC A++",
    fees: 45000,
    description:
      "One of the oldest and most prestigious medical colleges in India. Associated with Sir J.J. Hospital. Offers excellent clinical exposure and research opportunities. Hostel facilities available.",
    rating: 4.7,
    establishedYear: 1845,
    affiliation: "MUHS",
    placementRate: 92,
    phoneNumber: 912222665555,
    email: "dean@gmc.edu.in",
    website: "https://www.gmc.edu.in",
  },
  {
    image: ["https://pict.edu/history/images/7.jpg"],
    code: 105678,
    exam: "MHT-CET, JEE",
    name: "Pune Institute of Computer Technology",
    location: "Pune, Maharashtra",
    type: "Private",
    cutoff: 94,
    accreditation: "NAAC A",
    fees: 150000,
    description:
      "PICT is known for its excellent computer science and IT programs. Has modern labs, innovation center, and strong industry connections. Regular hackathons and coding competitions are organized.",
    rating: 4.4,
    establishedYear: 1983,
    affiliation: "Savitribai Phule Pune University",
    placementRate: 87,
    phoneNumber: 912027243311,
    email: "info@pict.edu",
    website: "https://www.pict.edu",
  },
  {
    image: [
      "https://home.iitd.ac.in/public/storage/uploads/IITD_1713248055.jpg",
    ],
    code: 200101,
    exam: "JEE Advanced",
    name: "Indian Institute of Technology Delhi",
    location: "New Delhi, Delhi",
    type: "Public (Institute of National Importance)",
    cutoff: 90,
    accreditation: "NAAC A++",
    fees: 220000,
    description:
      "IIT Delhi is one of the premier engineering and technology institutes in India. Renowned for its cutting-edge research, distinguished faculty, and strong alumni network. Offers a wide range of undergraduate and postgraduate programs.",
    rating: 4.9,
    establishedYear: 1961,
    affiliation: "Autonomous Institute",
    placementRate: 95,
    phoneNumber: 911126597135,
    email: "admissions@iitd.ac.in",
    website: "https://www.iitd.ac.in",
  },
  {
    image: [
      "https://techportal.in/wp-content/uploads/2023/11/iit-bombay-1024x425.jpg",
    ],
    code: 200202,
    exam: "JEE Advanced",
    name: "Indian Institute of Technology Bombay",
    location: "Mumbai, Maharashtra",
    type: "Public (Institute of National Importance)",
    cutoff: 95,
    accreditation: "NAAC A++",
    fees: 230000,
    description:
      "IIT Bombay is a globally recognized institute for engineering, science, and technology education. Features state-of-the-art facilities, a vibrant campus life, and excellent placement opportunities across various sectors.",
    rating: 4.9,
    establishedYear: 1958,
    affiliation: "Autonomous Institute",
    placementRate: 96,
    phoneNumber: 912225722545,
    email: "admissions@iitb.ac.in",
    website: "https://www.iitb.ac.in",
  },
  {
    image: [
      "https://cdn.thewire.in/wp-content/uploads/2020/12/14164827/EmRGSSuVMAUFofB.jpeg",
    ],
    code: 200303,
    exam: "JEE Advanced",
    name: "Indian Institute of Technology Madras",
    location: "Chennai, Tamil Nadu",
    type: "Public (Institute of National Importance)",
    cutoff: 97,
    accreditation: "NAAC A++",
    fees: 210000,
    description:
      "IIT Madras is known for its strong research focus and innovation ecosystem. Offers a wide range of programs in engineering, sciences, humanities, and management. Has a well-developed industrial consultancy and sponsored research division.",
    rating: 4.8,
    establishedYear: 1959,
    affiliation: "Autonomous Institute",
    placementRate: 94,
    phoneNumber: 914422578200,
    email: "admissions@iitm.ac.in",
    website: "https://www.iitm.ac.in",
  },
  {
    image: [
      "https://images.shiksha.com/mediadata/images/articles/1705320646phpUNQWwe.jpeg",
    ],
    code: 200404,
    exam: "JEE Advanced",
    name: "Indian Institute of Technology Kanpur",
    location: "Kanpur, Uttar Pradesh",
    type: "Public (Institute of National Importance)",
    cutoff: 96,
    accreditation: "NAAC A",
    fees: 215000,
    description:
      "IIT Kanpur has a rich academic heritage and is known for its pioneering work in various engineering and scientific disciplines. Features excellent infrastructure, including libraries, labs, and computing facilities.",
    rating: 4.7,
    establishedYear: 1959,
    affiliation: "Autonomous Institute",
    placementRate: 93,
    phoneNumber: 915122597992,
    email: "admissions@iitk.ac.in",
    website: "https://www.iitk.ac.in",
  },
  {
    image: ["https://coeamt.iitkgp.ac.in/img/carousel-2.jpg.png"],
    code: 200505,
    exam: "JEE Advanced",
    name: "Indian Institute of Technology Kharagpur",
    location: "Kharagpur, West Bengal",
    type: "Public (Institute of National Importance)",
    cutoff: 98,
    accreditation: "NAAC A++",
    fees: 200000,
    description:
      "The first IIT of India, IIT Kharagpur has a sprawling campus and a wide range of academic programs. Known for its strong engineering departments and a significant contribution to technical education in India.",
    rating: 4.6,
    establishedYear: 1951,
    affiliation: "Autonomous Institute",
    placementRate: 92,
    phoneNumber: 913222282221,
    email: "admissions@iitkgp.ac.in",
    website: "https://www.iitkgp.ac.in",
  },
  {
    image: [
      "https://images.shiksha.com/mediadata/images/1745235722phpZbT4mE.jpeg",
    ],
    code: 300101,
    exam: "BITSAT",
    name: "Birla Institute of Technology and Science, Pilani",
    location: "Pilani, Rajasthan",
    type: "Private (Deemed University)",
    cutoff: 97,
    accreditation: "NAAC A",
    fees: 450000,
    description:
      "BITS Pilani is a highly reputed private engineering and technology university. Known for its flexible academic structure, strong industry collaborations, and a significant focus on research and innovation.",
    rating: 4.8,
    establishedYear: 1964,
    affiliation: "Deemed University",
    placementRate: 90,
    phoneNumber: 911596245073,
    email: "admissions@pilani.bits-pilani.ac.in",
    website: "https://www.bits-pilani.ac.in",
  },
  {
    image: [
      "https://careermudhra.com/wp-content/uploads/vellore-institute-of-technology-tamil-nadu.png",
    ],
    code: 300202,
    exam: "VITEEE",
    name: "Vellore Institute of Technology",
    location: "Vellore, Tamil Nadu",
    type: "Private (Deemed University)",
    cutoff: 95,
    accreditation: "NAAC A++",
    fees: 198000,
    description:
      "VIT Vellore is a large and well-established private university offering a wide array of engineering, technology, and management programs. Known for its excellent infrastructure, diverse student population, and strong placement record.",
    rating: 4.7,
    establishedYear: 1984,
    affiliation: "Deemed University",
    placementRate: 91,
    phoneNumber: 914162202020,
    email: "admissions@vit.ac.in",
    website: "https://www.vit.ac.in",
  },
  {
    image: ["https://cse.jadavpuruniversity.in/public/upload/1694860515.jpeg"],
    code: 400101,
    exam: "WBJEE, JEE Main",
    name: "Jadavpur University",
    location: "Kolkata, West Bengal",
    type: "Public (State University)",
    cutoff: 98,
    accreditation: "NAAC A",
    fees: 12000,
    description:
      "Jadavpur University is a highly regarded state university with strong engineering, science, and arts departments. Known for its academic rigor and a significant contribution to research and development in the region.",
    rating: 4.6,
    establishedYear: 1955,
    affiliation: "State University",
    placementRate: 88,
    phoneNumber: 913324146666,
    email: "registrar@jadavpuruniversity.edu.in",
    website: "https://www.jadavpuruniversity.edu.in",
  },
  {
    image: [
      "https://content.jdmagicbox.com/v2/comp/chennai/r7/044pxx44.xx44.200625044734.l1r7/catalogue/anna-university-chennai-lwzcltkd46.jpg",
    ],
    code: 400202,
    exam: "TNEA",
    name: "Anna University",
    location: "Chennai, Tamil Nadu",
    type: "Public (State University)",
    cutoff: 99,
    accreditation: "NAAC A",
    fees: 50000,
    description:
      "Anna University is a prominent state technical university with numerous affiliated colleges. The main campus offers a wide range of engineering, technology, and architecture programs. Focuses on quality education and research.",
    rating: 4.5,
    establishedYear: 1978,
    affiliation: "State University",
    placementRate: 85,
    phoneNumber: 914422357004,
    email: "registrar@annauniv.edu",
    website: "https://www.annauniv.edu",
  },
  {
    image: ["https://itecgoi.in/instituteImages/279_3.JPG"],
    code: 200606,
    exam: "JEE Advanced",
    name: "Indian Institute of Technology Roorkee",
    location: "Roorkee, Uttarakhand",
    type: "Public (Institute of National Importance)",
    cutoff: 98,
    accreditation: "NAAC A",
    fees: 218000,
    description:
      "IIT Roorkee is one of the oldest technical institutions in India, with a strong emphasis on engineering and applied sciences. The campus has a rich history and offers a conducive environment for academic and research pursuits.",
    rating: 4.6,
    establishedYear: 1847,
    affiliation: "Autonomous Institute",
    placementRate: 90,
    phoneNumber: 911332285312,
    email: "admissions@iitr.ac.in",
    website: "https://www.iitr.ac.in",
  },
];

module.exports = { data: sampleListing };
